#!/bin/bash

#Attempt to clean the folder of files
# generated by attempts to build the
# JFX application using the associated script.

echo "   JFX cleaning script started"

#Clear files generated by makeJFXjar script
echo "   removing build folder. . ."
rm -rf build

echo "   removing app jar. . ."
rm -r App.jar

echo "   removing extraneous build-related files. . ."
rm -r manifest.txt
rm -r srcFiles.txt

echo "   end of JFX cleaning script"